<?php
return[
    "MSG_RESULT" => "result",
    "MSG_MESSAGE" => "message",
    "RESPONSE_MSG" => "response_msg",
    "MSG_TITLE" => "title", 
    "MSG_TYPE" => "type", 
    "MSG_ID" => "id",
    "MSG_UUID" => "uuid",
    "MSG_SUCCESS" => "success",
    "MSG_SUCCESS_TITLE" => "Success",
    "MSG_FAILURE" => "failure",
    "MSG_FAILURE_TITLE" => "Failure",
    "MSG_WARNING" => "warning",
    "MSG_WARNING_TITLE" => "Warning",
    "MSG_URL" => "url",
    "MSG_ERROR" => "error",
    "MSG_ERROR_TITLE" => "Error",
    "MSG_ERROR_TYPE" => "error-type",
    "MSG_DATA" => "data",
    "MSG_ENTITY_OBJ" => "entityOBJ",
    "MSG_OBJ" => "entityOBJ",
    "MSG_RESPONSE" => "response",
    "MSG_SESSION" => "session",
    "MSG_INSTANCE" => "instance",
    "MSG_HTML" => "html",
    "MSG_STOP_NOW" => "stop",


    "MSG_WRONG_REQUEST" => "Your Request is Wrong!", 
    "MSG_SUCCESS_TEXT" => "Data Saved Successfully.",
    "MSG_FAILURE_TEXT" => "Data cannot saved, please try again..",
    "MSG_NOT_FOUND" => "No Saved data found",
    "MSG_NO_EXIST_DATA" => "No existing data found",
    "VERSION_CONTROL_MESSAGE" => "Another user has updated this item while you were editing.",
    "TXT_PERMISSION_DEINED" => "You don't have permission to access this content", 
    "AUTHENTICATION_FAIL" => "Authentication failed",
    "LOGIN_SUCCESS" => "Login Successfully",
    "MSG_FORGET_PASSWORD" => "Forgot Password Notification from RootOpp",
    "MSG_SEND_EMAIL" => "An email was send to your email regarding on new password.Please login with this password.",
    "MSG_FAIL_RESET" => "Failed to reset password.",
    "MSG_EMAIL_FAILED" => "Email send failed", 
];
